name: Notify Discord on Release

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "New release: ${{ github.event.release.tag_name }} - ${{ github.event.release.html_url }}" }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
